# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# CERN Analysis Preservation is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

docs:
  build: ./docs/
  environment:
    - "DEBUG=True"
  volumes:
    - ./docs:/docs
  ports:
    - "80:80"
