name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  lint-pydocstyle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check compliance with Python docstring conventions
        run: |
          pip install pydocstyle
          ./run-tests.sh --check-pydocstyle

  lint-flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check compliance with pep8, pyflakes and circular complexity
        run: |
          pip install flake8
          ./run-tests.sh --check-flake8

  lint-check-manifest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check Python manifest completeness
        run: |
          pip install check-manifest
          ./run-tests.sh --check-manifest

  python-unit-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[all]

      - name: Run pytest
        run: ./run-tests.sh --check-pytest-unit

      - name: Codecov Coverage
        if: matrix.python-version == 3.8
        uses: codecov/codecov-action@v1
        with:
          files: coverage.xml

  python-e2e-vcr-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[all]

      - name: Run pytest
        env:
          TESTS_SERVER_HOST: 'https://localhost'
          TEST_E2E_TOKEN: 'token'
        run: ./run-tests.sh --check-pytest-e2e-vcr
